import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(33,GPIO.OUT)
GPIO.setup(35,GPIO.OUT)
GPIO.setup(36,GPIO.OUT)
GPIO.setup(37,GPIO.OUT)
GPIO.setup(38,GPIO.OUT)

# define LEDs pins

for x in range(0,5):
    GPIO.output(33,True)
    time.sleep(0.5)
    GPIO.output(33,False)
    time.sleep(0.5)
    GPIO.output(35,True)
    time.sleep(0.5)
    GPIO.output(35,False)
    time.sleep(0.5)
    GPIO.output(36,True)
    time.sleep(0.5)
    GPIO.output(36,False)
    time.sleep(0.5)
    GPIO.output(37,True)
    time.sleep(0.5)
    GPIO.output(37,False)
    time.sleep(0.5)
    GPIO.output(38,True)
    time.sleep(0.5)
    GPIO.output(38,False)
    time.sleep(0.5)
    GPIO.output(37,True)
    time.sleep(0.5)
    GPIO.output(37,False)
    time.sleep(0.5)
    GPIO.output(36,True)
    time.sleep(0.5)
    GPIO.output(36,False)
    time.sleep(0.5)
    GPIO.output(35,True)
    time.sleep(0.5)
    GPIO.output(35,False)
    time.sleep(0.5)
    
GPIO.cleanup()
